routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use app\Http\Controllers\DataController;
use app\Http\Controllers\LanguageController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/data', 'DataController');
Route::resource('/language', 'LanguageController');
Route::resource('/categories', 'CategoryController');
Route::resource('/homepage', 'HomepageController');

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    use HasFactory;
    
    protected $table='languages';
    protected $fillable = ['id','name'];  
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Language;


class LanguageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $languages = Language::paginate(5);
    
        return view('language.index',compact('languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('language.create');   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           
            'name' => 'required',
            ]);
               Language::create($request->all());
     
        return redirect()->route('language.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Language $language)
    {
        return view('language.show',compact('language'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Language $language)
    {
        return view('language.edit',compact('language'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Language $language)
    {
        $request->validate([
            'name' => 'required',
        ]);
    
        $language->update($request->all());
    
        return redirect()->route('language.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Language $language)
    { $language->delete();
        return redirect()->route('language.index');
    }
}

resources/views/language/create.blade.php
@extends('language.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('language.index') }}">Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('language.store') }}" method="POST">
        @csrf
        
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group" >
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/language/edit.blade.php
@extends('language.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('language.index') }}">Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('language.update',$language->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $language->name }}" class="form-control" >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/language/index.blade.php
@extends('language.layout')


@section('content')
<br>
<br>
<div style="text-align: center"><h1>Languages</h1></div>
<br>
<br>
   <div class="row-justify-content-center" style="text-align: center; font-family: Palatino Linotype;">
       <div class="col-lg-12 margin-tb">
           <div class="pull-right">
               <a class="btn btn-success" href="{{ route('language.create') }}"> Create</a>
           </div>
       </div>
   </div>
   <br>
   <br>
   <table class="table table-bordered">
       <tr>
           <th>No</th>
           <th>Name</th>
           <th width="280px">Action</th>
       </tr>
       @foreach ($languages as $language)
       <tr>
           <td>{{ $language->id }}</td>
           <td>{{ $language->name }}</td>
           <td>
               <form action="{{ route('language.destroy',$language->id) }}" method="POST">

                   <a class="btn btn-primary" href="{{ route('language.edit',$language->id) }}">Edit</a>
 
                   @csrf
                   @method('DELETE')
    
                   <button type="submit" class="btn btn-danger">Delete</button>
               </form>
           </td>
       </tr>
       @endforeach
   </table>
@endsection

resources/views/language/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Language</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
    <body>
<style>
   
   h1,h2 {
            font-family: Palatino Linotype;
            font-size: 45px;
            color: white;
            text-shadow: 2px 2px 15px yellow;
    }
    h3 {
        font-family: Palatino Linotype;
        font-size: 35px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
    }
    h5 {
        font-family: Palatino Linotype;
        font-size: 20px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
    }
    label, th, td, strong{ 
        font-family: Palatino Linotype;
        color: white;
    }
    body{
        background-image: url('https://b-f33-zpg.zdn.vn/1248775459659432309/4c93f2f0a05953070a48.jpg');
  		background-repeat: no-repeat;
  		background-attachment: fixed;
  		background-size: 100% 100%;
    }
    table{
        background-color: rgba(20, 20, 20, 0.6);

    }
    
      
         
</style>
<div class="container">
    @yield('content')
</div>
</body>
</html>