routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use app\Http\Controllers\DataController;
use app\Http\Controllers\LanguageController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/data', 'DataController');
Route::resource('/language', 'LanguageController');
Route::resource('/categories', 'CategoryController');
Route::resource('/homepage', 'HomepageController');

app/Models/Data.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Language;
use App\Models\Category;

class Data extends Model
{
   
    public $timestamps = false;
    protected $table = 'data';
    protected $fillable = [
        'name', 'amount', 'publisher','year','image_path'
    ];
    
    public function languages()
    {
        return $this->belongsToMany(Language::class, 'data_language','language_id', 'data_id');
    }

    public function categories()
        {
            return $this->belongsToMany(Category::class,'category_data', 'category_id', 'data_id');
        }
    
}

app/Http/Controllers/DataController.php
<?php

namespace App\Http\Controllers;

use App\Models\Data;
use App\Models\Language;
use App\Models\Category;
use App\Http\Requests\CreateDataRequest;
use App\Http\Requests\UpdateDataRequest;
use Illuminate\Http\Request;

class DataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $datas = Data::with('categories','languages')->paginate(5);

        return view('data.index',compact('datas'));
            
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {   
        $languages = Language::get();
        $categories = Category::get();
        return view('data.create', compact('categories','languages'));   
    }
        
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDataRequest $request)
    { //submit
        $request->all();
        $image = request()->file('image_path');
        $newImageName = time() . '-' . $request->name . '.' . 
        $request->image->extension();
        $request->image->move(public_path('images'), $newImageName);

        $data = Data::create([
            'name' => $request->input('name'),
            'amount' => $request->input('amount'),
            'publisher'=>$request->input('publisher'),
            'year'=>$request->input('year'),
            'image_path'=> $newImageName ,
            ]);
        $data->languages()->attach($request->input('languages')); 
        $data->categories()->attach($request->input('categories')); 
        return redirect()->route('data.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Data $data)
    {  
       return view('data.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    { //vao trang edit
        $data = Data::findOrFail($id); 
        $languages = Language::get();
        $categories = Category::get();
        
        $selectedLanguages =  $data->languages()->pluck('languages.id')->toArray();
        $selectedCategories = $data->categories()->pluck('categories.id')->toArray();
        return view('data.edit',compact('data','languages','categories','selectedCategories', 'selectedLanguages'));    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(UpdateDataRequest $request, $id)
    { 

        $data=Data::findOrFail($id);
        $request->all(); 
        
        $data->name = $request->input('name');
        $data->amount = $request->input('amount');
        $data->publisher = $request->input('publisher');
        $data->year = $request->input('year');       

        if($request->hasFile('image_path')) {
            $image = $request->file('image_path');
            $extension = $image->getClientOriginalExtension();
            $filename = time() . '-' . $request->name . '.' .$extension;    
            $image->move(public_path('images'),$filename);
            $data->image_path = $filename;
        }
        $data->update(); //save
        $data->languages()->sync($request->input('languages'));  
        $data->categories()->sync($request->input('categories'));  
       
        return redirect()->route('data.index')->with('success','Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { 
        Data::destroy($id);
        return redirect()->route('data.index');
    }
}

resources/views/data/create.blade.php
@extends('data.layout')
  
@section('content')
<br>
<br>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <h3>ADD BOOK</h3>
        </div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('data.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
    
    <div class="block" style="font-family: Palatino Linotype; width:400px; text-align:center;">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" >
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Amount:</strong>
                <input type="number" class="form-control" name="amount" placeholder="Amount"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Publisher:</strong>
                <input type="text" name="publisher" class="form-control" placeholder="Publisher">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Year:</strong>
                <input type="number" name="year" class="form-control" placeholder="Year">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <strong>Language:</strong>
            <select name="languages[]" class="form-control" multiple>
                @foreach($languages as $language)
                    <option value="{{ $language->id }}">{{ $language->name }}</option>
                @endforeach
            </select>
            <br>
                    <strong>Genre:</strong>
                    <select name="categories[]" class="form-control" multiple>
                    @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
        </div>
        <br>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <strong>Image:</strong>
                <input type="file" name="image">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center"> 
        <a class="btn btn-warning" href="{{ route('data.index') }} " style="font-family:Palatino Linotype;"> Back</a>
        <button type="submit" class="btn btn-success" style="font-family:Palatino Linotype;">Submit</button>
        </div>
    </div>
    
   
</form>
@endsection

resources/views/data/edit.blade.php
@extends('data.layout')
   
@section('content')
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
    <br>
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>EDIT</h3>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('data.update',$data->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <input type="hidden" name="id" value="{{ $data->id }}">
        <div class="block" style="font-family: Palatino Linotype; width:400px; text-align:center;">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $data->name }}" class="form-control" >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Amount:</strong>
                    <input type="number" name="amount" value="{{ $data->amount }}" class="form-control" >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Publisher:</strong>
                    <input type="text" name="publisher" value="{{ $data->publisher }}" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Year:</strong>
                    <input type="number" name="year" value="{{ $data->year }}" class="form-control">
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div>
                <strong>Language:</strong>
            <select name="languages[]" class="form-control" multiple>
                @foreach($languages as $language)                   
                    <option value="{{ $language->id }}"
                    {{ in_array($language->id, $selectedLanguages) ? 'selected':''}}>
                    {{$language ->name}}
                    </option>
                @endforeach
                </select>
                </div>
                <div>
                <strong>Genre:</strong>
                <select name="categories[]" class="form-control" multiple>
                @foreach($categories as $category)
                <option value="{{ $category->id }}"  
                {{ in_array($category->id, $selectedCategories) ? 'selected' : '' }}>
                {{ $category->name }}
                </option>
                @endforeach
                </select>
                </div>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <input type="file" name="image_path" value="{{$data->image_path}}">
                <label class="custom-file-input">Browse</lable>
            </div>
              <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <a class="btn btn-warning" href="{{ route('data.index') }}">Back</a>
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

   
    </form>


@endsection

resources/views/data/index.blade.php
@extends('data.layout1')
@section('content')
 
   @if ($message = Session::get('success'))
       <div class="alert alert-success">
           <p>{{ $message }}</p>
       </div>
   @endif 
   <table class="table table-bordered">
   <br>
       <tr>
           <th>No</th>
           <th>Image</th>
           <th>Name</th>
           <th>Amount</th>
           <th>Publisher</th>
           <th>Year</th>
           <th>Language</th>
           <th>Genre</th>
           <th width="280px">Action</th>
       </tr>
       @foreach ($datas as $i => $data)
       <tr>
            <td>{{ $i + 1 }}</td>
           <td>
           <img
            src="{{ asset('images/'. $data->image_path)}}"
            width="100" height="120"
            alt=""
            >
            </td> 
           <td>{{ $data->name }}</td>
           <td>{{ $data->amount }}</td>
           <td>{{ $data->publisher }}</td>
           <td>{{ $data->year }}</td>
           <td>
           @foreach($data->languages as $language) {{$language->name}}
            @if (!$loop->last) , @endif 
           @endforeach
           </td>
           <td>@foreach($data->categories as $category) {{ $category->name }}
           @if (!$loop->last) , @endif 
           @endforeach
           </td>
           <td>
        <form action="{{ route('data.destroy',$data->id) }}" method="POST">

            <a class="btn btn-warning" href="{{ route('data.show',$data->id) }}">Detail</a>

            <a class="btn btn-success" href="{{ route('data.edit',$data->id) }}">Edit</a>

            @csrf
            @method('DELETE')

            <button type="submit" onclick="return confirm ('Do you really want to delete?')" class="btn btn-danger" >Delete</button>
        </form>
           </td>
       </tr>
       @endforeach
   </table>
   <div class="pagination justify-content-center">
{!! $datas->links('pagination::bootstrap-4') !!}
   </div>


@endsection

resources/views/data/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>DeHanu Library</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
<body>

<style>
   
   h1,h2 {
            font-family: Palatino Linotype;
            font-size: 55px;
            color: white;
            text-shadow: 2px 2px 15px yellow;
    }
    h3 {
        font-family: Palatino Linotype;
        font-size: 45px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
    }
    h5 {
        font-family: Palatino Linotype;
        font-size: 25px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
        font-style: italic;
    }
    label, th, td { 
        font-family: Palatino Linotype;
        color: white;
        border-radius: 10px;
    }
    strong{ 
        font-family: Palatino Linotype;
        color: white;
        font-size: 20px;
        border-radius: 10px;
        text-shadow: 2px 2px 5px black;
    }
    .block {
        margin-left: auto;
        margin-right: auto;
        width: 8px
    }
    body{
        background-image: url('https://b-f33-zpg.zdn.vn/1248775459659432309/4c93f2f0a05953070a48.jpg');
  		background-repeat: no-repeat;
  		background-attachment: fixed;
  		background-size: 100% 100%;
    }
    table{
        background-color: rgba(20, 20, 20, 0.6);

    }
             
</style>

<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/data/layout1.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>DeHanu Library</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
<body>
<div class="container">
<div class="col-xs-12 col-sm-12 col-md-12 text-center">
       <div class="col-lg-12 margin-tb">
       
           <div class="row">
                <div class="col-sm-2" style="margin:15px 20px">
                    <img src="https://media0.giphy.com/media/1v0ySRY3f7gUuSeBIq/giphy.gif" width="200" height="150"
                    alt="">
                </div>
                
                        <div class="col-sm-6" style="margin:40px 50px">
                    <h1>DEHANU LIBRARY</h1>
                    <h5>_Knowledge is power_ <h5>
                       </div>
                
                <div class="col-sm-2" style="margin:15px 10px">
                    <img src="https://media0.giphy.com/media/1v0ySRY3f7gUuSeBIq/giphy.gif" width="200" height="150"
                    alt="">
                </div>
           </div>
           <div class="pull-right" style="font-family:Palatino Linotype;">
               <a class="btn btn-warning" href="{{ route('data.create') }}"> Create new book</a>
           </div>
       </div>
   </div>
   @yield('content')
   </div>
   </div>
<style> 
   h1,h2 {
            font-family: Palatino Linotype;
            font-size: 45px;
            color: white;
            text-shadow: 2px 2px 15px yellow;
    }
    h3 {
        font-family: Palatino Linotype;
        font-size: 35px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
    }
    h5 {
        font-family: Palatino Linotype;
        font-size: 20px;
        color: white;
        text-shadow: 2px 2px 5px yellow;
        font-style: italic;
    }
    label, th, td, strong{ 
        font-family: Palatino Linotype;
        color: white;
    }
    body{
        background-image: url('https://b-f33-zpg.zdn.vn/1248775459659432309/4c93f2f0a05953070a48.jpg');
  		background-repeat: no-repeat;
  		background-attachment: fixed;
  		background-size: 100% 100%;
    }
    table{
        background-color: rgba(20, 20, 20, 0.6);

    }         
</style>
</body>
</html>

resources/views/data/show.blade.php
@extends('data.layout')
  
@section('content')
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
    <br>
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>BOOK'S INFORMATION</h3>
            </div>
        </div>
    </div>
   
    <div class="row">
    <div class="col-sm-6">
        <img style="margin:35px 80px;"
            src="{{ asset('images/'. $data->image_path)}}"
            width="320" height="420"
            alt=""
        >
    </div>
        <div class="col-sm-4" style="margin:100px 3px ; background-color:rgba(20, 20, 20, 0.3) ; padding: 25px 20px 20px 30px ; border-radius:20px; box-shadow : 4px 4px 4px orange">

        <div class="text-center">
            <div class="form-group">
                <strong>Name:</strong>
                <strong>{{ $data->name }}</strong>
            </div>
        
            <div class="form-group">
                <strong>Amount:</strong>
                <strong>{{ $data->amount }}</strong>
            </div>
        
            <div class="form-group">
                <strong>Publisher:</strong>
                <strong>{{ $data->publisher }}</strong>
            </div>
       
            <div class="form-group">
                <strong>Year:</strong>
                <strong>{{ $data->year}}</strong>
            </div>
            <div class="form-group">
                <strong>Language:</strong>
                <strong>@foreach($data->languages as $language)
            {{$language->name}}
            @if (!$loop->last), @endif  @endforeach
            </strong>                
            </div>
            <div class="form-group">
                <strong>Genre:</strong>
                <strong>@foreach($data->categories as $category)
            {{ $category->name}} @if (!$loop->last), @endif @endforeach
                </strong>
            </div>
            <div class="text-center" style="font-family: Palatino Linotype;">
                <a class="btn btn-warning" href="{{ route('data.index') }}">Back</a>
            </div>
            </div>
        </div>
        
        
    </div>
@endsection